### ISSUE TITLE
Arrows in the 'Events' section not working

### ISSUE THREAD

**Issue by capy-on-caffeine** [c-d-a-o/cdao-site#3]
Using the arrows to switch between slides doesn't actually switch the slides. Right now, the only way around the issue is to scroll with the scroll bar (which is visible by the way)

**Comment by acdevs** [comment]
Yup! actually the problem lies in technique to slide, arrows actually scroll horizontally by 'scrollAmount(500)'  but when width of slides grow as in bigger displays, scrollAmount should be atleast half of the width, but its fixed at 500(px) (btw it works on my small display). 
Resolution:
1. To get offsetWidth of the slider-card and set scrollAmount(offsetWidth / 2). Or throw the whole technique out! Next,
2. Using arrows to actually display cards and animate the sliding transition into view! (redoing the CSS), that i personally prefer.
